### ISSUE TITLE
0.1.2 can't be started

### ISSUE THREAD

**Issue by freaktechnik** [tim-hellhake/opensensemap-adapter#5]
After updating to 0.1.2:
```
Failed to start add-on OpenSenseMap: Cannot find module '/home/node/.mozilla-iot/addons/opensensemap-adapter/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by freaktechnik** [comment]
I think the issue is that package.sh doesn't execute `npm run build` and neither does the release action.
